version: '3.8'

services:
  node:
    build:
      context: ./dockerfiles
      dockerfile: ./Dockerfile.service
    tmpfs:
      - /tmp
      - /run

    #
    # confg: systemd requires attaching cgroup file system volume with read-only access
    #
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

    #
    # confg: cluster size and port mappings
    #
    deploy:
      replicas: 3
    ports:
      - "1010-1012:2380"

    stdin_open: true
