version: '3.8'

services:
  node:
    build:
      context: ./dockerfiles
      dockerfile: ./Dockerfile.service
    tmpfs:
      - /tmp
      - /run
    volumes:
      #
      # running systemd requires attaching cgroup file system volume
      #
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

    #
    # cluster size and port mappings P
    #
    deploy:
      replicas: 3
    ports:
      - "1010-1012:2380"

    stdin_open: true
