version: '3.8'

name: etcd
services:
  node:
    build:
      dockerfile: ./centos8-etcd.dockerfile
    tmpfs:
      - /tmp
      - /run

    volumes:
      # copy service unit files
      - ./unit/etcd.service:/etc/systemd/system/etcd.service

    # cluster size and port mappings
    deploy:
      replicas: 3
    ports:
      - "1010-1012:2380"

    stdin_open: true
