version: '2.17'

services:

  ansible-control-node:
    build:
      context: ./ansible/docker
      dockerfile: ./Dockerfile

  etcd-node:
    build:
      context: ./etcd/docker
      dockerfile: ./Dockerfile
    stdin_open: true
    ports:
      - "1010-1012:2380"
