FROM miskiux/base-ha-psql

ENV ETCDVERSION=3.3.13

RUN curl -sL "https://storage.googleapis.com/etcd/v${ETCDVERSION}/etcd-v${ETCDVERSION}-linux-amd64.tar.gz" \
    | tar xz -C /usr/local/bin --strip=1 --wildcards --no-anchored etcd etcdctl

CMD ["/usr/lib/systemd/systemd"]